<?php
    $cart = $block->getLayout()->createBlock(\Magento\Checkout\Block\Cart::class);
    $items = $cart->getItems();
    $productIds = [];
    foreach ($items as $item) {
        $productIds[] = $item->getProduct()->getId();
    }

    // $productCollection = $block->getData('crosssell')->getItemsCollection()->setPageSize(10);
     //$productCollection->getSelect()->where('entity_id NOT IN(?)', $productIds);

?>
