<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<div class="footer_icon">
    <ul>
       <li class="bi-twitter"></li>
       <li class="bi-instagram"></li>
       <li class="bi-facebook"></li>
       <li class="bi-youtube"></li>
       <li class="bi-snapchat"></li>
    </ul>
</div>

<style>
.footer_icon ul {
  padding: 0;
  display: flex;
}

.footer_icon ul li {
  font-size: 25px;
  color: white;
  margin-left: 10px;
  list-style: none;
}
</style>

