<div class="footer-link">
    <div class="container">
        <div class="row float-right">
            <div class="col-3">
                <h5>HERE TO HELP</h5>
                <ul>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                </ul>
            </div>
            <div class="col-3">
                <h5>HERE TO HELP</h5>
                <ul>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                </ul>
            </div>
            <div class="col-3">
                <h5>HERE TO HELP</h5>
                <ul>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                </ul>
            </div>
            <div class="col-3">
                <h5>HERE TO HELP</h5>
                <ul>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<style>
    .footer-link ul {
        padding-left: 0;
    }

    .footer-link h5 {
        color: #f8f3e8;
        font-family: DrukWideBold;
        font-size:15px;
        line-height:20px;
        margin:0px 0px 9px;
        text-align:left;
        text-transform:uppercase;
        font-weight: 800;
    }

    .footer-link ul li {
        color:#f8f3e8;
        display:list-item;
        font-family:WorkSansRegular;
        line-height:28px;
        margin:5px 0px;
        text-align:left;
        font-size: 13px;
    }
</style>