<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$categoryFactory = $objectManager->create('Magento\Catalog\Model\ResourceModel\Category\CollectionFactory');
$categories = $categoryFactory->create()
    ->addAttributeToSelect('*')
    ->addAttributeToFilter('include_in_menu', 1)
    ->addAttributeToFilter('is_active', 1)
    ->addAttributeToSort('position', 'ASC')
?>

<div class="nav-right">
    <ul class="d-flex">
        <?php foreach($categories as $item) {  ?>
        <li> <?= $item->getName(); ?> </li>
        <?php } ?>
    </ul>
</div>

<style>
    li {
        text-transform: uppercase;
        list-style: none;
        font-size: 15px;
        font-weight: 600;
    }
</style>