<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>


<div class="nav-right">
    <ul class="d-flex" style="margin-top: 16px;">
        <li>tips & advice</li>
        <li style="margin-left: 10px;">about us</li>
    </ul>
</div>


<style>
   .nav-right li {
        text-transform: uppercase;
        list-style: none;
        font-size: 15px !important;
        font-weight: 600;
        color: white;
    }
</style>