
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>

<div>
    <div class="top-left d-flex">
         <div class="d-flex">
           <span>Location</span>  <i class="bi-chevron-down"></i>
         </div>
         <div class="d-flex" style="margin-left:20px">
          <span>Shops</span>  <i class="bi-geo-alt"></i>
         </div>
    </div>
</div>

<style>

.top-left span {
        font-size: 15px;
        color:white;
        text-transform: uppercase;
    }

.top-left i {
        font-size:20px;
        margin-left: 5px;
        color: white !important;
    }
</style>