<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
</head>
<div class="top-right">
    <ul class="d-flex ">
        <li> <i class="bi-search"></i> </li>
        <li> <i class="bi-person"></i> </li>
        <li> <i class="bi-heart"></i></li>
        <li> <i class="bi-cart"></i></li>
    </ul>
</div>



<style>
    .top-right ul>li i {
        font-size: 25px !important;
        margin-left: 20px;
        color: white !important;
    }


    .top-right ul li {
        list-style: none;
    }
</style>