<div class="footer-link">
    <div class="container d-flex justify-content-between">
            <div>
                <h5>HERE TO HELP</h5>
                <ul>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                </ul>
            </div>
            <div>
                <h5>HERE TO HELP</h5>
                <ul>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                </ul>
            </div>
            <div>
                <h5>HERE TO HELP</h5>
                <ul>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                </ul>
            </div>
            <div>
                <h5>HERE TO HELP</h5>
                <ul>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                    <li>Delivery Information and Return Policy</li>
                </ul>
            </div>
        </div>
    <!-- </div> -->
</div>

<style>

</style>