<div class="search-icon">
    <img src="<?= $this->getViewFileUrl('images/search-icon.png'); ?>" alt="" srcset="">
</div>

<div id="modal-search">
    <div class="modal-body-content">
        <input type="text" class="input-text loaded" id="modal-search-popup" placeholder="Type Here To Search" />
    </div>
</div>

<script type="text/javascript">
    require([
        "jquery",
        "Magento_Ui/js/modal/modal"
    ], function($, modal) {

        var options = {
            type: 'popup',
            responsive: true,
            buttons: []
            // buttons: [{
            //     text: $.mage.__('Ok'),
            //     class: '',
            //     click: function() {
            //         this.closeModal();
            //     }
            // }]
        };

        var popup = modal(options, $('#modal-search'));
        $(".search-icon img").click(function() {
            $('#modal-search').modal('openModal');
        });
    });
</script>
