<?php
$data = $block->getProduct();
$brand = $data->getAttributeText("brand");
$videoLink = $data->getData("video_link")
?>

<div class="container">
    <div class="row">
        <div class="col-6">
            Brand : <?= $brand ?>
        </div>
        <div class="col-6">
            <iframe width="420" height="315" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen src="<?= $videoLink ?>">
            </iframe>
        </div>
    </div>
</div>